patch auto-gen by /usr/local/sbin/gm under account cipher

diff --git a/Git-Daemon/gmv2 b/Git-Daemon/gmv2
--- a/Git-Daemon/gmv2
+++ b/Git-Daemon/gmv2
@@ -50,10 +50,10 @@ _exec_ops(){
   if [[ $OPER=="push" ]]; then
       git add --all  > /dev/null 2>&1
       git commit -m ${COMIT_MSG:-"patch auto-gen by ${0:0} under account $USER"}  > /dev/null 2>&1
-      if [[ $? -ne 1 || $? -ne 0 ]]; then
-        kill -9 $1 >/dev/null 2>&1
-        echo "Error encountered while commiting"
-      fi
+      # if [[ $? -ne 1 || $? -ne 0 ]]; then
+      #   kill -9 $1 >/dev/null 2>&1
+      #   echo "Error encountered while commiting"
+      # fi
   fi
   # check internet connectivity
   echo -ne "\033[1;33m Checking your connection...👀 \033[m"  > /dev/null 2>&1
