patch auto-gen by /usr/local/sbin/gm under account cipher

diff --git a/Git-Daemon/gmv2 b/Git-Daemon/gmv2
--- a/Git-Daemon/gmv2
+++ b/Git-Daemon/gmv2
@@ -53,9 +53,9 @@ _exec_ops(){
   echo -ne "\E[1;34m Script is ${OPER}ing updates --- 💭 \E[m"  > /dev/null 2>&1;
   echo -e "\n"  > /dev/null 2>&1
   git $OPER origin ${BRANCH:-"main"} > /dev/null 2>&1
-  if [[ !$? ]]; then
-    #statements
-    echo "Morph"
+  if [[ $? -ne 0 ]]; then
+    kill -9 $1
+    echo "Error encountered"
   fi
   kill -9 $1
 }
