patch auto-gen by /usr/local/sbin/gm under account cipher

diff --git a/Git-Daemon/gmv2 b/Git-Daemon/gmv2
--- a/Git-Daemon/gmv2
+++ b/Git-Daemon/gmv2
@@ -42,10 +42,18 @@ _setup_ssh(){
 }
 _exec_ops(){
   _setup_ssh
+  if [[ $? -ne 0 ]]; then
+    kill -9 $1 >/dev/null 2>&1
+    echo "Error encountered while setting up ssh"
+  fi
   cd ${DIRECTORY:-.}
   if [[ $OPER=="push" ]]; then
       git add --all  > /dev/null 2>&1
       git commit -m ${COMIT_MSG:-"patch auto-gen by ${0:0} under account $USER"}  > /dev/null 2>&1
+      if [[ $? -ne 0 ]]; then
+        kill -9 $1 >/dev/null 2>&1
+        echo "Error encountered while commiting"
+      fi
   fi
   # check internet connectivity
   echo -ne "\033[1;33m Checking your connection...👀 \033[m"  > /dev/null 2>&1
@@ -54,10 +62,10 @@ _exec_ops(){
   echo -e "\n"  > /dev/null 2>&1
   git $OPER origin ${BRANCH:-"main"} > /dev/null 2>&1
   if [[ $? -ne 0 ]]; then
-    kill -9 $1
-    echo "Error encountered"
+    kill -9 $1 >/dev/null 2>&1
+    echo "Error encountered while pushing"
   fi
-  kill -9 $1
+  kill -9 $1 >/dev/null 2>&1
 }
 _banner_(){
   echo ""
